nodeLinker: node-modules

# Enable immutable installs for CI (can be relaxed locally)
# enableImmutableInstalls: true

defaultSemverRangePrefix: '^'
# Optional: uncomment to use Yarn Berry plugins (future)
# plugins:
#   - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
#     spec: "@yarnpkg/plugin-workspace-tools"
